[package]
name = "toggler"
version = "0.1.0"
authors = ["Mark Pedersen <markrepedersen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = { version = "0.20", features = ["tokio-comp"] }
actix-web = "3"
serde = "1"
serde_json = "1"
toml = "0.5"