[package]
name = "switcharoo"
version = "0.1.0"
authors = ["Mark Pedersen <markrepedersen@gmail.com>"]
edition = "2018"

[features]
default = ["web"]
web = []

[dependencies]
redis = { version = "0.20", features = ["tokio-comp"] }
actix-web = "3"
actix-multipart = "0.3"
futures = "0.3"
serde = "1"
serde_json = "1"
toml = "0.5"
env_logger = "0.8"
sqlx = { version = "0.3", features = ["postgres"] }
dotenv = "0.15"
bcrypt = "0.8"
anyhow = "1"