version: "3.8"

services:
  switcharoo:
    build: .
    ports:
      - 8080:8080
  redis:
    image: redis:6.2.1-alpine3.13
    restart: always
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./redis/users.acl:/usr/local/etc/redis/users.acl:rw
      - ./redis/data:/data:rw
    ports:
      - 6379:6379