version: "3.8"

services:
  switcharoo:
    build: .
    ports:
      - 8080:8080
  redis:
    image: redis:6.2.1-alpine3.13
    restart: always
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./redis/users.acl:/usr/local/etc/redis/users.acl:rw
      - ./redis/data:/data:rw
    ports:
      - 6379:6379
  db:
    image: postgres:13.2
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./database/seed:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    env_file: .env
